import Membership from "@/components/Membership";
import useAuth from "@/hooks/useAuth";
import useSubscription from "@/hooks/useSubscription";
import { payments } from "@/lib/stripe";
import { getProducts, Product } from "@stripe/firestore-stripe-payments";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { GetStaticProps } from "next";

interface Props {
    products: Product[];
}

function Account({ products }: Props) {
    const { user } = useAuth();
    const subscription = useSubscription(user);

    console.log(products, subscription);

    return (
        <div>
            <Head>
                <title>Netflix - Account</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <header>
                <Link href="/">
                    <Image
                        src="https://rb.gy/ulxxee"
                        width={120}
                        height={120}
                        className="cursor-pointer object-contain"
                        alt=""
                    />
                </Link>
                <Link href="/account">
                    <Image
                        src="https://rb.gy/g1pwyx"
                        alt=""
                        className="cursor-pointer rounded"
                        width={35}
                        height={35}
                    />
                </Link>
            </header>

            <main className="pt-24">
                <div>
                    <h1 className=" text-3xl md:text-4xl">Account</h1>

                    <div className="-ml-0.5 flex items-center gap-x-1.5">
                        <Image
                            src="https://rb.gy/4vfk4r"
                            alt=""
                            className="h-7 w-7"
                            width={35}
                            height={35}
                        />
                        <p className="text-xs font-semibold text-[gray]/60">
                            Member since {subscription?.created}
                        </p>
                    </div>
                </div>

                <Membership />

                <div>
                    <h4>Plan Details</h4>

                    <div>
                        {/* {
                            products.filter(
                                (product) =>
                                    product.id === subscription?.product
                            )[0].name
                        } */}
                    </div>
                </div>
            </main>
        </div>
    );
}

export default Account;

export const getStaticProps: GetStaticProps = async () => {
    const products = await getProducts(payments, {
        includePrices: true,
        activeOnly: true,
    })
        .then((res) => res)
        .catch((error) => console.log(error.message));

    return {
        props: {
            products,
        },
    };
};
