import Table from "@/components/Table";
import useAuth from "@/hooks/useAuth";
import { loadCheckout, payments } from "@/lib/stripe";
import { getProducts, Product } from "@stripe/firestore-stripe-payments";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { HiCheck } from "react-icons/hi";
import { useState } from "react";
import Loader from "@/components/Loader";

interface Props {
    products: Product[];
}

function Plans({ products }: Props) {
    const { logout, user } = useAuth();
    const [selectedPlan, setSelectedPlan] = useState<Product>(products[2]);
    const [isBillingLoading, setIsBillingLoading] = useState(false);

    console.log(selectedPlan);

    function subscribeToPlan() {
        if (!user) return;

        loadCheckout(selectedPlan.prices[0].id);
        setIsBillingLoading(true);
    }

    console.log(products);

    return (
        <div>
            <Head>
                <title>Netflix - Plans</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/iconNetflix.png" />
            </Head>

            <header>
                <Link href="/login">
                    <Image
                        src="https://rb.gy/ulxxee"
                        alt="Netflix"
                        width={150}
                        height={90}
                        className="cursor-pointer object-contain"
                    />
                </Link>

                <button
                    className="text-lg font-medium hover:underline"
                    onClick={logout}
                >
                    Sign Out
                </button>
            </header>

            <main className=" pt-28 lg:w-[1000px] m-auto pb-12 transition-all md:px-10">
                <h1 className=" mb-3 text-3xl font-medium">
                    Choose the plan that&apos;s right for you
                </h1>

                <ul>
                    <li className="flex items-center gap-x-2 text-lg">
                        <HiCheck className="h-7 w-7 text-[#E50914]" /> Watch all
                        you want. Ad-free.
                    </li>
                    <li className="flex items-center gap-x-2 text-lg">
                        <HiCheck className="h-7 w-7 text-[#E50914]" />{" "}
                        Recommendations just for you.
                    </li>
                    <li className="flex items-center gap-x-2 text-lg">
                        <HiCheck className="h-7 w-7 text-[#E50914]" /> Change or
                        cancel your plan anytime.
                    </li>
                </ul>

                <div className="mt-4 flex flex-col space-y-4">
                    <div className="flex w-full items-center self-end md:w-3/5">
                        {products.map((product) => (
                            <div
                                key={product.id}
                                className={`planBox ${
                                    selectedPlan?.id === product.id
                                        ? "opacity-100"
                                        : "opacity-60"
                                }`}
                                onClick={() => setSelectedPlan(product)}
                            >
                                {product.name}
                            </div>
                        ))}
                    </div>

                    <Table products={products} selectedPlan={selectedPlan} />

                    <button
                        disabled={!selectedPlan || isBillingLoading}
                        className={`mx-auto w-11/12 rounded bg-[#E50914] py-4 text-xl shadow hover:bg-[#f6121d] md:w-[420px] ${
                            isBillingLoading && "opacity-60"
                        }`}
                        onClick={subscribeToPlan}
                    >
                        {isBillingLoading ? (
                            <Loader color="dark:fill-gray-300" />
                        ) : (
                            "Subscribe"
                        )}
                    </button>
                </div>
            </main>
        </div>
    );
}

export default Plans;

export async function getServerSideProps() {
    const products = await getProducts(payments, {
        includePrices: true,
        activeOnly: true,
    })
        .then((res) => res)
        .catch((error) => console.log(error.message));

    return { props: { products } };
}
